### ISSUE TITLE
Unable to download the shared bag file

### ISSUE THREAD

**Issue by ShigemichiMatsuzaki** [BIT-TYJ/SSGM#1]
Hi, thanks for the great work!

I would like to try your program, but I consistently fail to download the file you shared via Baiduyun.
Is it possible for you to upload the file in other cloud services like Google Drive or Dropbox?

Thank you,

**Comment by BIT-TYJ** [comment]
Sorry for taking so long to reply. I have uploaded a sample dataset to Google Drive. 
Welcome to communicate more!

**Comment by ShigemichiMatsuzaki** [comment]
Hi!
Thank you so much for the response!
I confirmed that I can download the file.

Thanks again for your work!
